name: Build and Test Project

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  build-test-push:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Check formatting
        run: nox -s lint

      - name: Run tests
        run: nox -s tests-3.11
